### PR TITLE
Add measure tests

### PR DESCRIPTION
**Pull request by tfarago**
A humble attempt to test the measure task. Not very elegant with all the file names, python-dependent and we have precision problems.

### CODE REVIEW

**Comment by matze** [comment]
> with all the file names

Doesn't matter, better to catch spurious problems.

> python-dependent

The tests are already Python dependent, so what? ;-)

Otherwise, looks good to me.

**Review by matze — APPROVED** [review]

**Comment by matze** [comment]
One thing: where do we put the input and reference data? I am a bit reluctant checking this in because it can make the repo grow unreasonably large.

**Comment by tfarago** [comment]
Absolutely. In this case I can create data on the fly (will do that later, also in such a way that there won't be the precision priblem). Otherwise, we should put it where we can both access it. LSDF?

**Comment by matze** [comment]
LSDF is not accessible from anywhere. I just moved the data for the existing tests to one of our outside visible machines and added a `setup.sh` to download them. But if you can create them on-the-fly, that's even better.

**Comment by tfarago** [comment]
I had to play with `run.py` but I didn't do tremendous changes and all tests pass.

**Comment by matze** [comment]
Looks good. Once you have merged the `measure` tasks you can merge this as well.

**Comment by tfarago** [comment]
This is good to go as well.

**Pull request merged**
